before_install:
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.5
  - 2.2.0
  - 2.2.4
  - 2.2.5
  - 2.3.0
  - 2.3.1

script: "bundle exec rake spec"

notifications:
  disabled: false
  recipients:
    - johannes.opper@gmail.com
